package com.tcs.entity;

import jakarta.persistence.*;

/**
 * Entity representing user login credentials and roles.
 * Mapped to the "login" table in the database.
 */
@Entity
@Table(name = "login")
public class Login {

    /**
     * Unique ID for each login entry. Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique username used for authentication.
     */
    @Column(unique = true, nullable = false)
    private String username;

    /**
     * Encrypted password for the user.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Role of the user. Can be either "ADMIN" or "UNDERWRITER".
     */
    @Column(nullable = false)
    private String role;

    /**
     * Default constructor required by JPA.
     */
    public Login() {}

    /**
     * Parameterized constructor for initializing login entities.
     *
     * @param username the user's username
     * @param password the user's password (hashed)
     * @param role     the user's role ("ADMIN" or "UNDERWRITER")
     */
    public Login(String username, String password, String role) {
        this.username = username;
        this.password = password;
        this.role = role;
    }

    // Getters and setters

    public Long getId() { return id; }

    public void setId(Long id) { this.id = id; }

    public String getUsername() { return username; }

    public void setUsername(String username) { this.username = username; }

    public String getPassword() { return password; }

    public void setPassword(String password) { this.password = password; }

    public String getRole() { return role; }

    public void setRole(String role) { this.role = role; }
}
